const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('peliVeli', {
  getConfig:      ()       => ipcRenderer.invoke('config:get'),
  setConfig:      (c)      => ipcRenderer.invoke('config:set', c),
  getSettings:    ()       => ipcRenderer.invoke('settings:get'),
  setSettings:    (s)      => ipcRenderer.invoke('settings:set', s),
  getScanMeta:    ()       => ipcRenderer.invoke('scanmeta:get'),
  getGames:       ()       => ipcRenderer.invoke('games:get'),
  scanGames:      ()       => ipcRenderer.invoke('games:scan'),
  enrichGames:    ()       => ipcRenderer.invoke('games:enrich'),
  reEnrichGames:  ()       => ipcRenderer.invoke('games:reenrich'),
  launchGame:     (g)      => ipcRenderer.invoke('games:launch', g),
  listFonts:      ()       => ipcRenderer.invoke('fonts:list'),
  getHiddenIds:   ()       => ipcRenderer.invoke('hidden:get'),
  hideGame:       (id)     => ipcRenderer.invoke('hidden:hide', id),
  unhideGame:     (id)     => ipcRenderer.invoke('hidden:unhide', id),
  getDebugLogPath:()       => ipcRenderer.invoke('debug:logPath'),
  setTitlebarTheme:(opts)  => ipcRenderer.invoke('titlebar:setTheme', opts),
  fetchOcById:    (gameId) => ipcRenderer.invoke('oc:fetchById', gameId),
  setGameOc:      (data)   => ipcRenderer.invoke('games:setOc', data),
  refreshOneGame: (gameId) => ipcRenderer.invoke('games:refreshOne', gameId),
  getCustomThemes:  ()        => ipcRenderer.invoke('themes:getCustom'),
  installTheme:     ()        => ipcRenderer.invoke('themes:install'),
  deleteTheme:      (fname)   => ipcRenderer.invoke('themes:delete', fname),
  exportTheme:      (settings)=> ipcRenderer.invoke('themes:export', settings),
  getThemesDir:     ()        => ipcRenderer.invoke('themes:getDir'),
  onScanProgress:   (cb) => { ipcRenderer.on('scan:progress',   (_, m) => cb(m)); return () => ipcRenderer.removeAllListeners('scan:progress') },
  onEnrichProgress: (cb) => { ipcRenderer.on('enrich:progress', (_, m) => cb(m)); return () => ipcRenderer.removeAllListeners('enrich:progress') },
  openExternal:     (url) => ipcRenderer.invoke('shell:openExternal', url),
  addManualGame:    ()        => ipcRenderer.invoke('games:addManual'),
  renameGame:       (id, title) => ipcRenderer.invoke('games:rename', { id, title }),
})
